// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Perks from './Perks';
import Testimonials from './Testimonials';

export {
	Hero,
	Perks,
	Testimonials,
};

export const components = {
	hero: Hero,
	perks: Perks,
	testimonials: Testimonials,
};
